<?php

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| Here you may define all of your model factories. Model factories give
| you a convenient way to create models for testing and seeding your
| database. Just tell the factory how a default model should look.
|
*/
$occupation=[
'Construction Project Manager',
'Project Builder',
'Engineering Manager',
'Production Manager (Mining)',
'Child Care Centre Manager',
'Medical Administrator',
'Nursing Clinical Director',
'Primary Health Organisation Manager',
'Welfare Centre Manager',
'Accountant (General)',
'Management Accountant',
'Taxation Accountant',
'External Auditor',
'Internal Auditor',
'Actuary',
'Land Economist',
'Valuer',
'Ship\'s Engineer',
'Ship\'s Master',
'Ship\'s Officer',
'Architect',
'Landscape Architect',
'Cartographer',
'Other Spatial Scientist',
'Surveyor',
'Chemical Engineer',
'Materials Engineer',
'Civil Engineer',
'Geotechnical Engineer',
'Quantity Surveyor',
'Structural Engineer',
'Transport Engineer',
'Electrical Engineer',
'Electronics Engineer',
'Industrial Engineer',
'Mechanical Engineer',
'Production or Plant Engineer',
'Aeronautical Engineer',
'Agricultural Engineer',
'Biomedical Engineer',
'Engineering Technologist',
'Environmental Engineer',
'Naval Architect',
'Agricultural Consultant',
'Agricultural Scientist',
'Forester',
'Medical Laboratory Scientist',
'Veterinarian',
'Physicist (Medical Physicist only)',
'Early Childhood (Pre-Primary School) Teacher',
'Secondary School Teacher',
'Special Needs Teacher',
'Teacher of the Hearing Impaired',
'Teacher of the Sight Impaired',
'Special Education Teachers nec',
'Medical Diagnostic Radiographer',
'Medical Radiation Therapist',
'Nuclear Medicine Technologist',
'Sonographer',
'Optometrist',
'Orthotist or Prosthetist',
'Chiropractor',
'Osteopath',
'Occupational Therapist',
'Physiotherapist',
'Podiatrist',
'Audiologist',
'Speech Pathologist',
'General Practitioner',
'Anaesthetist',
'Specialist Physician (General Medicine)',
'Cardiologist',
'Clinical Haematologist',
'Medical Oncologist',
'Endocrinologist',
'Gastroenterologist',
'Intensive Care Specialist',
'Neurologist',
'Paediatrician',
'Renal Medicine Specialist',
'Rheumatologist',
'Thoracic Medicine Specialist',
'Specialist Physicians nec',
'Psychiatrist',
'Surgeon (General)',
'Cardiothoracic Surgeon',
'Neurosurgeon',
'Orthopaedic Surgeon',
'Otorhinolaryngologist',
'Paediatric Surgeon',
'Plastic and Reconstructive Surgeon',
'Urologist',
'Vascular Surgeon',
'Dermatologist',
'Emergency Medicine Specialist',
'Obstetrician and Gynaecologist',
'Ophthalmologist',
'Pathologist',
'Diagnostic and Interventional Radiologist',
'Radiation Oncologist',
'Medical Practitioners nec',
'Midwife',
'Nurse Practitioner',
'Registered Nurse (Aged Care)',
'Registered Nurse (Child and Family Health)',
'Registered Nurse (Community Health)',
'Registered Nurse (Critical Care and Emergency)',
'Registered Nurse (Developmental Disability)',
'Registered Nurse (Disability and Rehabilitation)',
'Registered Nurse (Medical)',
'Registered Nurse (Medical Practice)',
'Registered Nurse (Mental Health)',
'Registered Nurse (Perioperative)',
'Registered Nurse (Surgical)',
'Registered Nurse (Paediatrics)',
'Registered Nurses nec',
'ICT business Analyst',
'Systems Analyst',
'Analyst Programmer',
'Developer Programmer',
'Software Engineer',
'Computer Network and Systems Engineer',
'Telecommunications Engineer',
'Telecommunications Network Engineer',
'Barrister',
'Solicitor',
'Clinical Psychologist',
'Educational Psychologist',
'Organisational Psychologist',
'Psychotherapist',
'Psychologists nec',
'Social Worker',
'Civil Engineering Draftsperson',
'Civil Engineering Technician',
'Electrical Engineering Draftsperson',
'Electrical Engineering Technician',
'Radio Communications Technician',
'Telecommunications Field Engineer',
'Telecommunications Network Planner',
'Telecommunications Technical Officer or Technologist',
'Automotive Electrician',
'Motor Mechanic (General)',
'Diesel Motor Mechanic',
'Motorcycle Mechanic',
'Small Engine Mechanic',
'Sheetmetal Trades Worker',
'Metal Fabricator',
'Pressure Welder',
'Welder (First Class)',
'Fitter (General)',
'Fitter and Turner',
'Fitter-Welder',
'Metal Machinist (First Class)',
'Locksmith',
'​Panelbeater',
'Bricklayer',
'Stonemason',
'Carpenter and Joiner',
'Carpenter',
'Joiner',
'Painting trades workers',
'Glazier',
'Fibrous Plasterer',
'Solid Plasterer',
'Wall and Floor Tiler',
'Plumber (General)',
'Airconditioning and Mechanical Services Plumber',
'Drainer',
'Gasfitter',
'Roof plumber',
'Electrician (General)',
'Electrician (Special Class)',
'Lift Mechanic',
'Airconditioning and Refrigeration Mechanic',
'Electrical Linesworker',
'Technical Cable Jointer',
'Electronic Equipment Trades Worker',
'Electronic Instrument Trades Worker (General)',
'Electronic Instrument Trades Worker (Special Class)',
'Chef',
'​Cabinetmaker',
'Boat Builder and Repairer',
'Shipwright'
];

$category=[
'Accounting',
'Administrative/Clerical',
'Arts/Entertainment/Media',
'Automotive',
'Biotechnology',
'Business',
'Construction',
'Customer Service',
'Education',
'Engineering',
'Executive',
'Facilities',
'Financial Services',
'Government',
'Healthcare',
'Hospitality',
'Human Resources',
'Information Technology',
'Insurance',
'Law Enforcement',
'Legal',
'Manufacturing/Production',
'Marketing',
'Other',
'Real Estate',
'Retail/Wholesale',
'Sales',
'Science',
'Telecommunications',
'Transportation/Warehouse'
    ];



$factory->define(App\User::class, function (Faker\Generator $faker) use ($occupation){
    return [
        'name' => $faker->unique()->word,
        'email' => $faker->unique()->email,
        'contact_email' => $faker->unique()->email,
        'password' => bcrypt(str_random(10)),
        
        'objective' => $faker->randomElement($occupation),
        'salary' => $faker->optional($weight = 0.8)->numberBetween($min = 100, $max = 10000),
        'employment_type' => $faker->randomElement($array = array ('Full-time','Part-time','remote','temporary')),
        
         'first_name' => $faker->firstName($gender = null|'male'|'female'),
         'last_name' => $faker->lastName,
         'city' => $faker->city,
         'birth' => $faker->optional($weight = 0.5, $default = '2000-01-01')->date($format = 'Y-m-d', $max = '2000-01-01'),
         'sex' => $faker->randomElement($array = array ('male','female')),
         'phone' => $faker->e164PhoneNumber,
        
         'education_qualification' => $faker->randomElement($array = array ('High school or equivalent','Associate','Bachelor','Master','Doctor')),
         'education_occupation' => $faker->randomElement($occupation),
         'education_university' => $faker->text($maxNbChars = 50),
         'education_from_month'=>$faker->monthName($max = 'now'), 
         'education_to_month'=>$faker->monthName($max = 'now'),
         'education_from_year'=>$faker->numberBetween($min = 1990, $max = 2000),  
         'education_to_year'=>$faker->numberBetween($min = 2001, $max = 2010),  
    
         'exp1_title' => $faker->randomElement($occupation),
         'exp1_company' => $faker->company,
         'exp1_from_month'=>$faker->monthName($max = 'now'), 
         'exp1_to_month'=>$faker->monthName($max = 'now'),
         'exp1_from_year'=>$faker->numberBetween($min = 2005, $max = 2010),  
         'exp1_to_year'=>$faker->numberBetween($min = 2011, $max = 2017),  
         'exp1_description'=>$faker->text($maxNbChars = 1000), 

        
         'exp2_title' => $faker->randomElement($occupation),
         'exp2_company' => $faker->company,
         'exp2_from_month'=>$faker->monthName($max = 'now'), 
         'exp2_to_month'=>$faker->monthName($max = 'now'),
         'exp2_from_year'=>$faker->numberBetween($min = 2000, $max = 2005),  
         'exp2_to_year'=>$faker->numberBetween($min = 2006, $max = 2010), 
         'exp2_description'=>$faker->text($maxNbChars = 1000),  

         'description'=>$faker->text($maxNbChars = 3000),  
        
        
    ];
});

 $factory->define(App\Firm::class, function (Faker\Generator $faker) use ($occupation,$category){
     return [
          'title' => $faker->company,
          'city' => $faker->city,
          'category' => $faker->randomElement($category),
          'website' => $faker->domainName,
          'email' => $faker->unique()->email,
          'phone' => $faker->optional($weight = 0.8)->e164PhoneNumber,
          'show_website' => $faker->randomElement($array = array ('1','0')),
          'show_email' => $faker->randomElement($array = array ('1','0')),
          'show_phone' => $faker->randomElement($array = array ('1','0')),
          'description'=>$faker->text($maxNbChars = 3000),  
          'user_id' => $faker->unique()->numberBetween($min = 1, $max = 50),
     ];
 });


 $factory->define(App\Job::class, function (Faker\Generator $faker) use ($occupation,$category){
     return [
         'position' => $faker->randomElement($occupation), 
         'category' => $faker->randomElement($category), 
         'city' => $faker->city,
         'salary' => $faker->optional($weight = 0.8)->numberBetween($min = 100, $max = 10000),
         'education' => $faker->randomElement($array = array ('High school or equivalent','Associate','Bachelor','Master','Doctor')),
         'experience' => $faker->randomElement($array = array ('no matter','<0,5 year','0,5-1 year','1-2 years','2-3 years','3-5 years','5-10 years','>10 years')),
         'employment_type' => $faker->randomElement($array = array ('Full-time','Part-time','remote','temporary')),
         'description'=>$faker->text($maxNbChars = 3000),
         'firm_id' => $faker->numberBetween($min = 1, $max = 50),

   
        
     ];
});   